# Generated by Django 3.1.7 on 2021-03-15 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exer_1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Numbers',
        ),
    ]
