# Generated by Django 3.1.7 on 2021-04-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exer_1', '0006_auto_20210402_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='temp',
            field=models.FloatField(),
        ),
    ]
