# Generated by Django 3.1.7 on 2021-04-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='temp',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
