# Generated by Django 3.1.7 on 2021-03-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
