# Generated by Django 3.1.7 on 2021-03-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_1', '0002_auto_20210315_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='number',
            field=models.IntegerField(blank=True),
        ),
    ]
